CSHARP/OENIK_PROG4HF_2020_1_I4N3OE/Sexshop.Web/Models/Toy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sexshop.Web.Models
{
    public class Toy
    {
        [Display(Name = "Toy ID")]
        [Required]
        public int ID { get; set; }

        [Display(Name = "Toy Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Toy Brand")]
        [Required]
        public string Brand { get; set; }

        [Display(Name = "Toy Price")]
        [Required]
        public int Price { get; set; }
    }
}

CSHARP/OENIK_PROG4HF_2020_1_I4N3OE/Sexshop.Web/Models/ToyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sexshop.Web.Models
{
    public class ToyViewModel
    {
        public Toy EditedToy { get; set; }
        public List<Toy> ListOfToys { get; set; }
    }
}

CSHARP/OENIK_PROG4HF_2020_1_I4N3OE/Sexshop.Web/Controllers/ToyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sexshop.Logic;
using AutoMapper;
using Sexshop.Web.Models;
using Sexshop.Data;
using Sexshop.Repository;

namespace Sexshop.Web.Controllers
{
    enum Tables { CUSTOMER, PRODOUCT, REVIEW, PURCHASE };

    public class ToyController : Controller
    {
        ILogic logic;
        IMapper mapper;
        ToyViewModel vm;

        public ToyController()
        {
            logic = new ToyLogic();
            mapper = MapperFactory.CreateMapper();

            vm = new ToyViewModel();
            vm.EditedToy = new Toy();
            var toys = logic.ReadProducts();
            vm.ListOfToys = mapper.Map<IList<Data.PRODUCT>, List<Models.Toy>>(toys);
        }

        private Toy GetToyModel(int id)
        {
            PRODUCT toy = logic.ReadProduct(id);
            return mapper.Map<Data.PRODUCT,Models.Toy>(toy);
        }

        // GET: Toy
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("ToyIndex", vm);
        }

        // GET: Toy/Details/5
        public ActionResult Details(int id)
        {
            return View("ToyDetails", GetToyModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.DeleteProduct(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedToy = GetToyModel(id);
            return View("ToyIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Toy toy, string editAction)
        {
            if(ModelState.IsValid && toy != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.CreateProduct(toy.ID, toy.Name, toy.Brand, toy.Price);
                }
                else
                {
                    bool success = logic.UpdateProduct(toy.ID, toy.Name, toy.Brand, toy.Price);
                    if(!success) TempData["editResult"] = "Edit FAIL";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedToy = toy;
                return View("ToyIndex", vm);
            }
        }
    }
}

CSHARP/OENIK_PROG4HF_2020_1_I4N3OE/Sexshop.Web/Views/Toy/ToyDetails.cshtml
@model Sexshop.Web.Models.Toy
@{
    ViewBag.Title = "ToyDetails";
}

<h2>Datasheet of one toy</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>The ID for the toy</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Brand)</td>
        <td>@Html.DisplayFor(m => m.Brand)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>

</table>

CSHARP/OENIK_PROG4HF_2020_1_I4N3OE/Sexshop.Web/Views/Toy/ToyEdit.cshtml
@model Sexshop.Web.Models.Toy

<h2>Edit one toy</h2>

@using (Html.BeginForm("Edit", "Toy"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Brand)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Brand)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Price)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG4HF_2020_1_I4N3OE/Sexshop.Web/Views/Toy/ToyIndex.cshtml
@model Sexshop.Web.Models.ToyViewModel

@{
    ViewBag.Title = "ToyIndex";
}

<h2>Toys Index</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("ToyEdit", Model.EditedToy)

@Html.Partial("ToyList", Model.ListOfToys)

CSHARP/OENIK_PROG4HF_2020_1_I4N3OE/Sexshop.Web/Views/Toy/ToyList.cshtml
@model IEnumerable<Sexshop.Web.Models.Toy>

<h2>List of toys</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(m => m.First().Brand)</th>
        <th>@Html.DisplayNameFor(m => m.First().Name)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Edit</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(m => item.Brand)</td>
            <td>@Html.DisplayFor(m => item.Name)</td>
            <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID})</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ID })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
        </tr>
    }
</table>
}